version: '3.8'

services:
  backend:
    build: .
    container_name: teamhub-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/teamhub
      - JWT_SECRET=supersecretjwt
    depends_on:
      - db
    volumes:
      - .:/app
    command: ./wait-for-db.sh

  db:
    image: postgres:14
    container_name: teamhub-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: teamhub
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: